# Generated by Django 4.2 on 2026-04-13 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodmart', '0002_remove_order_status_remove_order_total_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('shipped', 'Shipped'), ('delivered', 'Delivered')], default='pending', max_length=20),
        ),
    ]
