# Generated by Django 4.2 on 2026-04-14 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodmart', '0003_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
    ]
