# Generated by Django 4.2 on 2026-04-14 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodmart', '0004_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default=1, upload_to='products/'),
            preserve_default=False,
        ),
    ]
